# -*- coding: utf-8 -*-
"""3D-like Generative Poster Creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJpN1AY12AuaGntTyDjLoZO434HeqY2D

### Creating 3D-like Effects with 2D Tricks in Python

To make a generative poster look 3D-like using only 2D elements, we can leverage several visual cues that our brains interpret as depth. Here, we'll demonstrate two common tricks:

1.  **Shadows and Transparency**: By drawing a slightly offset, darker, and semi-transparent version of an object behind it, we create the illusion that light is casting a shadow, implying the object is lifted from the background.
2.  **Layering and Overlap**: Placing objects in front of or behind others automatically creates a sense of depth. Objects that obscure parts of other objects are perceived as being closer to the viewer.
"""

import matplotlib.pyplot as plt
import numpy as np

# Helper function to create a blob shape
def create_blob(center_x, center_y, radius, num_points=100, irregularity=0.2):
    angles = np.linspace(0, 2 * np.pi, num_points, endpoint=False)
    radii = radius + irregularity * radius * (np.random.rand(num_points) - 0.5)
    x = center_x + radii * np.cos(angles)
    y = center_y + radii * np.sin(angles)
    return x, y

# --- Setup the plot ----
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_aspect('equal')
ax.set_facecolor('#f0f0f0') # Light gray background
ax.set_xlim(0, 10)
ax.set_ylim(0, 10)
ax.axis('off')

# List of primary/vibrant colors
colors = ['#FF0000', '#0000FF', '#FFFF00', '#00FF00', '#FF7F00', '#9400D3'] # Red, Blue, Yellow, Green, Orange, Indigo

# Generate a random number of blobs (e.g., between 3 and 7)
num_blobs = np.random.randint(3, 8)

blobs_data = []
for i in range(num_blobs):
    center_x = np.random.uniform(1.5, 8.5)
    center_y = np.random.uniform(1.5, 8.5)
    radius = np.random.uniform(0.8, 2.0)
    color = np.random.choice(colors)

    # Store blob data for proper z-order sorting
    blobs_data.append({
        'center_x': center_x,
        'center_y': center_y,
        'radius': radius,
        'color': color,
        'zorder': i * 2 # Each blob and its shadow gets 2 zorder levels
    })

# Sort blobs by y-coordinate to simulate further ones being drawn first
# This creates a more natural layering effect (objects with smaller y are "further")
blobs_data.sort(key=lambda b: b['center_y'])

for blob_info in blobs_data:
    center_x = blob_info['center_x']
    center_y = blob_info['center_y']
    radius = blob_info['radius']
    color = blob_info['color']
    zorder = blob_info['zorder']

    # Reduced irregularity for rounder blobs
    current_irregularity = np.random.uniform(0.1, 0.3)
    blob_x, blob_y = create_blob(center_x, center_y, radius, irregularity=current_irregularity)

    # Shadow for the blob - further reduced offset
    shadow_offset_x = np.random.uniform(0.02, 0.08)
    shadow_offset_y = np.random.uniform(-0.02, -0.08)

    # Create the shadow coordinates by offsetting the *exact* blob coordinates
    shadow_x = blob_x + shadow_offset_x
    shadow_y = blob_y + shadow_offset_y

    ax.fill(shadow_x, shadow_y, color='black', alpha=0.2, zorder=zorder)

    # Main blob (no edgecolor)
    ax.fill(blob_x, blob_y, color=color, zorder=zorder + 1, edgecolor=None, linewidth=0)


plt.title(f'Generative Poster with {num_blobs} Random Blobs and Shadows', fontsize=14)
plt.show()