# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tj1UOjohN310NHH4N4Yev4k6QfW_7OGU
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

# Helper function to create a blob shape
def create_blob(center_x, center_y, radius, num_points=100, irregularity=0.2):
    angles = np.linspace(0, 2 * np.pi, num_points, endpoint=False)
    radii = radius + irregularity * radius * (np.random.rand(num_points) - 0.5)
    x = center_x + radii * np.cos(angles)
    y = center_y + radii * np.sin(angles)
    return x, y

def generate_poster_plot(num_blobs_input, irregularity_factor=0.2):
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_aspect('equal')
    ax.set_facecolor('#f0f0f0') # Light gray background
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.axis('off')

    # List of primary/vibrant colors
    colors = ['#FF0000', '#0000FF', '#FFFF00', '#00FF00', '#FF7F00', '#9400D3'] # Red, Blue, Yellow, Green, Orange, Indigo

    blobs_data = []
    for i in range(num_blobs_input):
        center_x = np.random.uniform(1.5, 8.5)
        center_y = np.random.uniform(1.5, 8.5)
        radius = np.random.uniform(0.8, 2.0)
        color = np.random.choice(colors)

        blobs_data.append({
            'center_x': center_x,
            'center_y': center_y,
            'radius': radius,
            'color': color,
            'zorder': i * 2
        })

    # Sort blobs by y-coordinate for layering
    blobs_data.sort(key=lambda b: b['center_y'])

    for blob_info in blobs_data:
        center_x = blob_info['center_x']
        center_y = blob_info['center_y']
        radius = blob_info['radius']
        color = blob_info['color']
        zorder = blob_info['zorder']

        current_irregularity = np.random.uniform(irregularity_factor - 0.1, irregularity_factor + 0.1)
        blob_x, blob_y = create_blob(center_x, center_y, radius, irregularity=current_irregularity)

        # Shadow for the blob
        shadow_offset_x = np.random.uniform(0.02, 0.08)
        shadow_offset_y = np.random.uniform(-0.02, -0.08)
        shadow_x = blob_x + shadow_offset_x
        shadow_y = blob_y + shadow_offset_y

        ax.fill(shadow_x, shadow_y, color='black', alpha=0.2, zorder=zorder)
        ax.fill(blob_x, blob_y, color=color, zorder=zorder + 1, edgecolor=None, linewidth=0)

    plt.title(f'Generative Poster with {num_blobs_input} Random Blobs and Shadows', fontsize=14)
    return fig

# --- Streamlit App ----
st.set_page_config(page_title='3D-like Generative Poster', layout='centered')

st.title('3D-like Generative Poster with 2D Tricks')
st.write('슬라이더를 사용하여 블롭의 개수를 조절하고 나만의 포스터를 생성해보세요!')

# Sidebar controls
with st.sidebar:
    st.header('포스터 설정')
    num_blobs_slider = st.slider('블롭 개수 선택', min_value=1, max_value=10, value=4, step=1)
    irregularity_slider = st.slider('불규칙성 조절', min_value=0.0, max_value=0.5, value=0.2, step=0.05)

if st.button('포스터 생성!'):
    fig = generate_poster_plot(num_blobs_slider, irregularity_slider)
    st.pyplot(fig)

st.markdown("""
---
### 3D 효과 원리

이 포스터는 다음 두 가지 시각적 트릭을 사용하여 3D 같은 효과를 냅니다:

1.  **그림자 및 투명도**: 각 객체 뒤에 약간 오프셋되고 어두우며 반투명한 버전을 그려 그림자를 연출합니다. 이는 객체가 배경에서 떠 있는 듯한 착시 효과를 줍니다.
2.  **레이어링 및 겹침**: 객체를 다른 객체 앞에 배치하거나 뒤에 배치하여 깊이감을 부여합니다. 다른 객체의 일부를 가리는 객체는 더 가까이 있는 것으로 인식됩니다.
""")